cardsapp/urls.py
from django.urls import path
from cardsapp import views

app_name = 'cardsapp'

urlpatterns = [
	path('', views.HomeView.as_view(), name='home'),
	path('<str:deck>/cards/', views.DeckView.as_view(), name='cards'),
]

flashcards/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
	path('admin/', admin.site.urls),
	path('flashcards/', include('cardsapp.urls')),
]

cardsapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Deck(models.Model):
	name = models.CharField(max_length=128)
	description  = models.CharField(max_length=256, blank=True)
	owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='decks')
	is_public = models.BooleanField(default=False)
	is_editable = models.BooleanField(default=False)

	def __str__(self):
		return self.name

	def flashcard_count(self):
		return self.cards.count()

class Flashcard(models.Model):
	question = models.CharField(max_length=256)
	answer = models.TextField()
	code = models.TextField(blank=True)

	# related_field, for reverse queries
	# < Deck_object >.cards.all()
	deck = models.ForeignKey(Deck, on_delete=models.CASCADE, related_name='cards')
	
	owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='cards')

	def __str__(self):
		return self.question

cardsapp/views.py
from django.shortcuts import render
from django.views import View
from django.views.generic import ListView
from cardsapp.models import Deck, Flashcard

# https://docs.djangoproject.com/en/3.1/topics/class-based-views/intro/#handling-forms-with-class-based-views
class HomeView(View):
	template_name = 'cardsapp/index.html'

	def get(self, request):
		decks = Deck.objects.all()
		ctx ={'decks': decks}
		return render(request, self.template_name, ctx)

class DeckView(ListView):
	paginate_by = 2
	context_object_name = 'cards'
	template_name = 'cardsapp/cardlist.html'

	def get_queryset(self):
		deck = Deck.objects.get(name=self.kwargs['deck'])
		return deck.cards.all()

	def get_context_data(self, **kwargs):
		args = super(ListView, self).get_context_data(**kwargs)
		args['deck'] = self.kwargs['deck']
		return args

cardsapp/templates/cardbase.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
			integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2"
			crossorigin="anonymous"
		/>
		<link rel="stylesheet" href="{% static 'css/cardbase.css' %}" />
		{% block head %}
		{% endblock head %}

		<title>{% block title %}{% endblock title %}</title>
	</head>

	<body>
		<div class="container border-bottom d-flex justify-content-center site-name">
			<h1>FLASHCARDS</h1>
		</div>
		{% block content %}
		{% endblock content %}

		<script
			src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
			integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
			integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
			crossorigin="anonymous"
		></script>
		<script
			src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js"
			integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s"
			crossorigin="anonymous"
		></script>
		<script src="{% static 'js/base.js' %}"></script>
		{% block script %}
		{% endblock %}
	</body>
</html>

cardsapp/templates/cardsapp/cardlist.html
{% extends "cardbase.html" %}

{% block content %}
<section class="container mt-3 mb-5">
	<div class="headers">{{ deck }}</div>
	<div class="row cardContainer inactive">
		{% for card in cards %}
		<div class="col col-sm-4 card card2">
			<div class="side front">
				<div class="card-body">
					<h2>{{ card.question }}</h2>
				</div>
			</div>
			<div class="side back">
				<div class="card-body">
					<p>{{ card.answer }}</p>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</section>

{# pagination #}
<div class="container">
	{% if is_paginated %}
	<nav area-label="...">
		<ul class="pagination">
			{% if page_obj.has_previous %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.previous_page_number }}"
					>&laquo;</a
				>
			</li>
			{% else %}
			<li class="disabled page-item"><span class="page-link">&laquo;</span></li>
			{% endif %}

			{% for i in paginator.page_range %}
			{% if page_obj.number == i %}
			<li class="active page-item">
				<span class="page-link"
					>{{ i }} <span class="sr-only">(current)</span></span
				>
			</li>
			{% else %}
			<li class="page-item">
				<a class="page-link" href="?page={{ i }}">{{ i }}</a>
			</li>
			{% endif %}
			{% endfor %}
			{% if page_obj.has_next %}
			<li class="page-item">
				<a class="page-link" href="?page={{ page_obj.next_page_number }}"
					>&raquo;</a
				>
			</li>
			{% else %}
			<li class="disabled page-item"><span class="page-link">&raquo;</span></li>
			{% endif %}
		</ul>
	</nav>
	{% else %}
	<p>No more pages</p>
	{% endif %}
</div>

{% endblock content %}

cardsapp/templates/cardsapp/index.html
{% extends 'cardbase.html' %}
{% block content %}
<section class="container mt-3">
	<div class="d-flex headers grey-text">Dashboard</div>
	<div class="row row-cols-3 mt-2">
		{% for deck in decks %}
		<div class="col d-flex align-items-stretch">
			<div class="card bg-light flex-fill">
				<h5 class="card-header">{{ deck.name }}</h5>
				<div class="card-body">
					<p class="card-text">{{ deck.description }}</p>
				</div>
				<div class="card-footer">
					<a class="btn btn-primary" href="{% url 'cardsapp:cards' deck=deck.name %}">{{ deck.flashcard_count }} card{{ deck.flashcard_count|pluralize }}</a>
				</div>
			</div>
		</div>
		{% endfor %}
	</div>
</section>
{% endblock content %}